[spr] changes to helios2 this commit is based on
Created using jj-spr 1.3.6-beta.1

[skip ci]

diff --git a/build/buildctl b/build/buildctl
--- a/build/buildctl
+++ b/build/buildctl
@@ -309,8 +309,12 @@ build() {
             LOGFILE="$_LOGFILE"
             built_packages_p5m $SCRIPT
         else
-            PATH=$PATH:. $SCRIPT -r $PKGSRVR $build_flags $extra_flags || \
+            PATH=$PATH:. $SCRIPT -r $PKGSRVR $build_flags $extra_flags
+            if (($? != 0)); then
+                typeset log="`ls -1tr *.log | tail -1`"
+                [ -n "$log" ] && cp "$log" ../last-failure.log
                 logerr "Unable to run $SCRIPT"
+            fi
             [ -z "$extra_flags" ] && built_packages_sh $SCRIPT
         fi
         popd >/dev/null
@@ -434,13 +438,19 @@ reap_slot() {
     typeset -i ret=0
 
     case $stat in
-        0)  logmsg -n "-- Job $slot ($job) terminated normally"
-            ;;
-        *)  logmsg -e "-- Job $slot ($job) terminated with status $stat"
-            note -e "***** BUILD ERROR ***** ($job/$stat)"
-            builderr+=($job)
-            ret=1
-            ;;
+        0)      logmsg -n "-- Job $slot ($job) terminated normally"
+                ;;
+        127)    logmsg -e "-- Job $slot ($job) terminated with status $stat"
+                # 127 is not considered an error because it reflects a job
+                # which went away while we were not waiting for something to
+                # exit. That race may be worth closing some day but for now
+                # move on.
+                ;;
+        *)      logmsg -e "-- Job $slot ($job) terminated with status $stat"
+                note -e "***** BUILD ERROR ***** ($job/$stat)"
+                builderr+=($job)
+                ret=1
+                ;;
     esac
     unset slots[$slot]
     return $ret
@@ -465,30 +475,28 @@ clear_slots() {
 
 nextslot=
 wait_for_slot() {
-    # Check for any idle slots
-    for i in `seq 0 $threads`; do
-        [ -z "${slots[$i]}" ] && nextslot=$i && return
-    done
-
-    typeset slot=
     typeset -i stat=0
+    typeset slot=
+    typeset pid=
 
     # Wait for a slot to terminate
     while :; do
         wait -fn -p pid ${slots[*]}
         stat=$?
-        (( stat == 169 )) && continue               # SIGINFO
-        (( stat == 141 )) && continue               # SIGPIPE
-        (( stat == 144 )) && nextslot= && return    # SIGUSR1
-        if (( stat == 127 )); then                  # No jobs left
-            clear_slots $stat
-            nextslot=0
-            return
-        fi
+        case $stat in
+            169)    continue ;;                         # SIGINFO
+            141)    continue ;;                         # SIGPIPE
+            144)    nextslot=; return ;;                # SIGUSR1
+            127)                                        # No jobs left
+                clear_slots $stat
+                nextslot=0
+                return ;;
+        esac
+
         [ -n "$pid" ] || continue
         slot=${slotpid[$pid]}
         [ -n "$slot" ] && break
-        logmsg -n "Unknown pid $pid terminated $s"
+        logmsg -n "Unknown pid $pid terminated $stat"
     done
 
     if reap_slot $slot $stat; then
@@ -498,6 +506,21 @@ wait_for_slot() {
     else
         nextslot=
     fi
+}
+
+find_slot() {
+    # Check for any idle slots
+    for i in `seq 0 $threads`; do
+        [ -z "${slots[$i]}" ] && nextslot=$i && return
+    done
+
+    wait_for_slot
+}
+
+wait_for_expensive_slot() {
+    while (( `count_expensive` > ETHROTTLE )); do
+        wait_for_slot
+    done
 }
 
 wait_for_jobs() {
@@ -676,9 +699,7 @@ parallel_build() {
                 # number of expensive jobs has dropped low enough.
                 if [ $newloc -le 0 -o ${#queue[@]} -le ${#expensive[@]} ]; then
                     logmsg -n "-- $tgt, waiting for number of jobs to drop"
-                    while [ `count_expensive` -gt $ETHROTTLE ]; do
-                        wait_for_slot
-                    done
+                    wait_for_expensive_slot
                 else
                     logmsg -n "-- $tgt, relocating to $newloc/${#queue[@]}"
                     _queue=("${queue[@]:0:newloc}")
@@ -694,7 +715,7 @@ parallel_build() {
 
         if [ -z "$nextslot" ]; then
             logmsg "-- Waiting for spare job slot for $tgt"
-            wait_for_slot
+            find_slot
             [ -n "$nextslot" ] || break
         fi
 
@@ -735,6 +756,9 @@ parallel_build() {
 
     date
     logmsg "Total build time: $(print_elapsed $((`date +%s` - build_start)))"
+
+    [ -n "$builderr" ] && return 1
+    return 0
 }
 
 usage() {
@@ -901,7 +925,6 @@ case "$1" in
         usage
         ;;
 esac
-
 
 # Vim hints
 # vim:ts=4:sw=4:et:
